import type { Metadata } from "next";
import { PageHeader } from "@/components/PageHeader";
import { ContractTable, LiveStats, RecentEvents } from "@/components/LiveStats";
import { Card } from "@/components/ui";
import results from "@/lib/results.json";

export const metadata: Metadata = { title: "Transparency" };

const REPO_URL = process.env.NEXT_PUBLIC_REPO_URL; // e.g. https://github.com/<org>/<repo>

const invariantLabels: Record<string, string> = {
  invariant_I1_solvency: "I1 · Pool stays solvent",
  invariant_I2_totalCollateral: "I2 · Collateral totals match",
  invariant_I3_totalDebt: "I3 · Debt totals match",
  invariant_I4_noOvershoot: "I4 · A glide never overshoots 1.25",
  invariant_I5_noGlideAboveComfort: "I5 · No glide above 1.25",
  invariant_I6_tokenBalance: "I6 · Pool holds all collateral",
  invariant_I7_glideDominatesCliff: "I7 · Glide loses less than the cliff (no backstop)",
};

const gasRows: [keyof NonNullable<typeof results.gas>, string][] = [
  ["poke_1_block", "poke, 1 block accrued"],
  ["poke_100_blocks", "poke, 100 blocks accrued"],
  ["poke_idle", "poke, nothing to do"],
  ["pokeMany_20", "pokeMany, 20 users"],
  ["borrow", "borrow"],
  ["cliff_liquidate", "CliffPool.liquidate"],
];

const impact = (bps: number) => (bps === 0 ? "0.00%" : `−${(bps / 100).toFixed(2)}%`);

export default function TransparencyPage() {
  const inv = results.invariants;
  const totalTests = (results.tests?.passed ?? 0) + (inv?.rows.length ?? 0);
  return (
    <div className="mx-auto max-w-6xl space-y-4 px-4 pb-20 pt-10 sm:px-6">
      <PageHeader title="Transparency">
        Everything the pools hold and owe is public. The numbers below are read live from the contracts or generated by the test
        suite; none are typed in by hand.
      </PageHeader>

      <LiveStats />

      <Card title="Contracts">
        <ContractTable />
      </Card>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card title="Tests" description={`Generated ${new Date(results.generatedAt).toISOString().slice(0, 10)} by scripts/collect-results.mjs`}>
          <p className="num text-3xl font-semibold">{totalTests} passing</p>
          <p className="mt-1 text-sm text-muted">
            Unit, fuzz (1,000 runs each), attack scenarios, a crash replay and 50 simulator parity vectors, plus the invariants below.
          </p>
          {inv && (
            <table className="num mt-4 w-full text-sm">
              <caption className="mb-2 text-left text-muted">
                Invariants, {inv.rows[0].runs.toLocaleString("en-US")} runs × depth {inv.depth} ({inv.rows[0].calls.toLocaleString("en-US")} random calls each)
              </caption>
              <tbody className="divide-y divide-border">
                {inv.rows.map((r) => (
                  <tr key={r.name}>
                    <th scope="row" className="py-1.5 pr-3 text-left font-normal">{invariantLabels[r.name] ?? r.name}</th>
                    <td className={`py-1.5 text-right font-medium ${r.passed ? "text-safe" : "text-glide"}`}>{r.passed ? "Holds" : "Fails"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </Card>

        <Card title="Security" description="Static analysis and attack tests">
          {results.slither && (
            <p className="text-sm">
              Slither ran <span className="num">{results.slither.detectors}</span> detectors and reported{" "}
              <span className="num">{results.slither.results}</span> results. Every one is triaged as fixed, accepted or a false
              positive, with reasons, in <code className="font-mono">docs/security.md</code>.
            </p>
          )}
          <p className="mt-3 text-sm">
            Seven attacks are run against the contracts in tests.
            {results.attackA1 && (
              <>
                {" "}In the headline one, an attacker dumps the AMM and pokes a victim: with no price guard the victim loses{" "}
                <span className="num font-medium">{results.attackA1.naiveLossMusd} mUSD</span>; with Soft Landing’s oracle band
                the sale is skipped and they lose <span className="num font-medium">{results.attackA1.guardedLossMusd} mUSD</span>.
              </>
            )}
          </p>
          <p className="mt-3 text-sm text-muted">
            Found and fixed by the invariant tests: a backstop that closed the whole position re-created the cliff. It now sells
            only enough to get back to 1.25. Known limit: under back-to-back price gaps, the backstop costs about the same as a
            cliff liquidation.
          </p>
          {REPO_URL ? (
            <a href={`${REPO_URL}/blob/main/docs/security.md`} className="mt-3 inline-block text-sm underline underline-offset-4">
              Security write-up and threat model
            </a>
          ) : (
            <p className="mt-3 text-sm text-muted">
              Full write-up: <code className="font-mono">docs/security.md</code> and <code className="font-mono">docs/threat-model.md</code>.
            </p>
          )}
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {results.slippage && (
          <Card title="One dump vs many slices" description="Same AMM, same liquidity (1,000 mETH deep)">
            <table className="num w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left text-muted">
                  <th scope="col" className="py-2 pr-3 font-medium">Selling {results.slippage.totalSoldMeth} mETH</th>
                  <th scope="col" className="py-2 pr-3 font-medium">Slippage</th>
                  <th scope="col" className="py-2 font-medium">Price left behind</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                <tr>
                  <th scope="row" className="py-2 pr-3 text-left font-normal text-cliff">One cliff dump</th>
                  <td className="py-2 pr-3">{(results.slippage.cliffSlippageBps / 100).toFixed(2)}%</td>
                  <td className="py-2">{impact(results.slippage.cliffPriceImpactBps)}</td>
                </tr>
                <tr>
                  <th scope="row" className="py-2 pr-3 text-left font-normal text-safe">{results.slippage.slices} glide slices</th>
                  <td className="py-2 pr-3">{(results.slippage.glideSlippageBps / 100).toFixed(2)}%</td>
                  <td className="py-2">{impact(results.slippage.glidePriceImpactBps)}</td>
                </tr>
              </tbody>
            </table>
            <p className="mt-2 text-sm text-muted">Small slices move the price less, and that is also what stops liquidation cascades.</p>
          </Card>
        )}
        {results.gas && (
          <Card title="Gas" description="Each call as its own transaction">
            <table className="num w-full text-sm">
              <tbody className="divide-y divide-border">
                {gasRows.map(([k, label]) => (
                  <tr key={k}>
                    <th scope="row" className="py-1.5 pr-3 text-left font-normal">{label}</th>
                    <td className="py-1.5 text-right">{results.gas[k].toLocaleString("en-US")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        )}
      </div>

      <Card title="Recent unwinds" description="Glides and backstops in Soft Landing, liquidations in the cliff pool">
        <RecentEvents />
      </Card>
    </div>
  );
}
