// Downloads historical ETH/USDT candles once and writes trimmed JSON to web/public/crashes/, so the
// site and the CLI work offline. Source: Binance public market-data archive (data.binance.vision),
// daily 1-minute kline files. Usage: node sim/fetch-crashes.mjs
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { inflateRawSync } from "node:zlib";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "web", "public", "crashes");
mkdirSync(outDir, { recursive: true });

const SOURCE = "Binance public data archive (data.binance.vision), ETHUSDT spot 1-minute klines, close prices";

const CRASHES = [
  { id: "mar-2020", label: "Black Thursday, 12–13 March 2020", days: ["2020-03-12", "2020-03-13"], every: 1 },
  { id: "may-2021", label: "19 May 2021 crash", days: ["2021-05-19"], every: 1 },
  {
    id: "jun-2022",
    label: "June 2022 deleveraging, 10–19 June",
    days: ["2022-06-10", "2022-06-11", "2022-06-12", "2022-06-13", "2022-06-14", "2022-06-15", "2022-06-16", "2022-06-17", "2022-06-18", "2022-06-19"],
    every: 5, // 10 days: keep every 5th minute (5-minute closes)
  },
  { id: "aug-2024", label: "5 August 2024 sell-off, 4–5 August", days: ["2024-08-04", "2024-08-05"], every: 1 },
];

/** Minimal zip reader for a single-entry archive (stored or deflated). */
function unzipSingle(buf) {
  // find the central directory entry to get reliable sizes (local headers may use data descriptors)
  const eocd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  if (eocd < 0) throw new Error("not a zip");
  const cdOffset = buf.readUInt32LE(eocd + 16);
  const method = buf.readUInt16LE(cdOffset + 10);
  const compSize = buf.readUInt32LE(cdOffset + 20);
  const localOffset = buf.readUInt32LE(cdOffset + 42);
  const nameLen = buf.readUInt16LE(localOffset + 26);
  const extraLen = buf.readUInt16LE(localOffset + 28);
  const start = localOffset + 30 + nameLen + extraLen;
  const data = buf.subarray(start, start + compSize);
  if (method === 0) return data;
  if (method === 8) return inflateRawSync(data);
  throw new Error(`unsupported zip method ${method}`);
}

async function day(date) {
  const url = `https://data.binance.vision/data/spot/daily/klines/ETHUSDT/1m/ETHUSDT-1m-${date}.zip`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const csv = unzipSingle(Buffer.from(await res.arrayBuffer())).toString("utf8");
  // columns: open time, open, high, low, close, ...
  return csv
    .trim()
    .split("\n")
    .map((line) => line.split(","))
    .filter((cols) => /^\d+$/.test(cols[0]))
    .map((cols) => ({ t: Number(cols[0]), close: Number(cols[4]) }));
}

for (const c of CRASHES) {
  const rows = (await Promise.all(c.days.map(day))).flat().sort((a, b) => a.t - b.t);
  const kept = rows.filter((_, i) => i % c.every === c.every - 1);
  const prices = kept.map((r) => Number(r.close.toFixed(2)));
  const min = Math.min(...prices);
  const out = {
    id: c.id,
    label: c.label,
    source: SOURCE,
    interval_seconds: 60 * c.every,
    start: new Date(rows[0].t > 1e14 ? rows[0].t / 1000 : rows[0].t).toISOString(),
    prices,
  };
  writeFileSync(join(outDir, `${c.id}.json`), JSON.stringify(out));
  const drawdown = ((prices[0] - min) / prices[0]) * 100;
  console.log(`${c.id}: ${prices.length} steps, start ${prices[0]}, min ${min} (−${drawdown.toFixed(1)}%), end ${prices.at(-1)}`);
}

// Synthetic whipsaw: −20%, +15%, −20%, +20%, each leg over 120 one-minute steps, from 3,000.
{
  const legs = [-0.2, 0.15, -0.2, 0.2];
  const prices = [3000];
  for (const leg of legs) {
    const from = prices[prices.length - 1];
    const to = from * (1 + leg);
    for (let i = 1; i <= 120; i++) prices.push(Number((from + ((to - from) * i) / 120).toFixed(2)));
  }
  writeFileSync(
    join(outDir, "whipsaw.json"),
    JSON.stringify({
      id: "whipsaw",
      label: "Synthetic whipsaw: −20%, +15%, −20%, +20%",
      source: "Synthetic (generated by sim/fetch-crashes.mjs)",
      interval_seconds: 60,
      start: null,
      prices,
    }),
  );
  console.log(`whipsaw: ${prices.length} steps (synthetic)`);
}
