// Exports contract ABIs from Foundry's build output (as const, for viem/wagmi types) to web/lib/abis,
// indexer/abis and keeper/src/abis, and copies contracts/deployments/active.json to web/lib/deployments.json when it exists.
// Run `forge build` in contracts/ first. Usage: node scripts/export-abis.mjs
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const dests = [
  ["web/lib/abis", join(root, "web", "lib", "abis")],
  ["indexer/abis", join(root, "indexer", "abis")],
  ["keeper/src/abis", join(root, "keeper", "src", "abis")],
];

const contracts = [
  ["SoftLandingPool", "softLandingPoolAbi"],
  ["CliffPool", "cliffPoolAbi"],
  ["MockToken", "mockTokenAbi"],
  ["MockOracle", "mockOracleAbi"],
  ["MockAMM", "mockAmmAbi"],
  ["SliceRouter", "sliceRouterAbi"],
  ["PythOracleAdapter", "pythOracleAdapterAbi"],
];

if (!existsSync(out)) {
  console.error("contracts/out not found. Run `forge build` in contracts/ first.");
  process.exit(1);
}
for (const [label, dest] of dests) {
  mkdirSync(dest, { recursive: true });
  const index = [];
  for (const [name, exportName] of contracts) {
    const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
    writeFileSync(
      join(dest, `${name}.ts`),
      `// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.\n` +
        `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
    );
    index.push(`export { ${exportName} } from "./${name}";`);
  }
  writeFileSync(join(dest, "index.ts"), `// Generated by scripts/export-abis.mjs. Do not edit.\n${index.join("\n")}\n`);
  console.log(`abi  ${contracts.length} contracts -> ${label}`);
}

const active = join(root, "contracts", "deployments", "active.json");
if (existsSync(active)) {
  copyFileSync(active, join(root, "web", "lib", "deployments.json"));
  console.log("deployments/active.json -> web/lib/deployments.json");
} else {
  console.log("no contracts/deployments/active.json yet; web keeps its placeholder deployments.json");
}
